config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers tokens: "oauth/tokens"
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations",
    invitations: "invitations",
    passwords: "passwords",
    confirmations: "confirmations"
  }

  devise_scope :user do
    get "/enter", to: "registrations#new", as: :sign_up
    get "/confirm-email", to: "confirmations#new"
    delete "/sign_out", to: "devise/sessions#destroy"
  end

  get "/r/mobile", to: "deep_links#mobile"
  get "/.well-known/apple-app-site-association", to: "deep_links#aasa"

  scope "(/locale/:locale)", defaults: { locale: nil } do
    get "/locale/:locale", to: "stories#index"

    draw :admin

    namespace :stories, defaults: { format: "json" } do
      resource :feed, only: [:show] do
        resource :pinned_article, only: %w[show update destroy]

        get ":timeframe", to: "feeds#show", as: :timeframe
      end
    end

    namespace :api, defaults: { format: "json" } do
      scope module: :v0,
            constraints: ApiConstraints.new(version: 0, default: true) do
        resources :articles, only: %i[index show create update] do
          collection do
            get "me(/:status)", to: "articles#me", as: :me, constraints: { status: /published|unpublished|all/ }
            get "/:username/:slug", to: "articles#show_by_slug", as: :slug
            get "/latest", to: "articles#index", defaults: { sort: "desc" }
          end
        end
        resources :comments, only: %i[index show]
        resources :videos, only: [:index]
        resources :podcast_episodes, only: [:index]
        resources :users, only: %i[show] do
          collection do
            get :me
          end
        end
        resources :tags, only: [:index]
        resources :follows, only: [:create] do
          collection do
            get :tags
          end
        end
        namespace :followers do
          get :users
          get :organizations
        end
        resources :readinglist, only: [:index]
        resources :webhooks, only: %i[index create show destroy]

        resources :listings, only: %i[index show create update]
        get "/listings/category/:category", to: "listings#index", as: :listings_category
        get "/analytics/totals", to: "analytics#totals"
        get "/analytics/historical", to: "analytics#historical"
        get "/analytics/past_day", to: "analytics#past_day"
        get "/analytics/referrers", to: "analytics#referrers"

        resources :health_checks, only: [] do
          collection do
            get :app
            get :database
            get :cache
          end
        end

        resources :profile_images, only: %i[show], param: :username
        resources :organizations, only: [:show], param: :username do
          resources :users, only: [:index], to: "organizations#users"
          resources :listings, only: [:index], to: "organizations#listings"
          resources :articles, only: [:index], to: "organizations#articles"
        end
        resource :instance, only: %i[show]
      end
    end

    namespace :notifications do
      resources :counts, only: [:index]
      resources :reads, only: [:create]
    end

    namespace :incoming_webhooks do
      get "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#index", as: :mailchimp_unsubscribe_check
      post "/mailchimp/:secret/unsubscribe", to: "mailchimp_unsubscribes#create", as: :mailchimp_unsubscribe
    end

    resources :messages, only: [:create]
    resources :articles, only: %i[update create destroy] do
      patch "/admin_unpublish", to: "articles#admin_unpublish"
    end
    resources :article_mutes, only: %i[update]
    resources :comments, only: %i[create update destroy] do
      patch "/hide", to: "comments#hide"
      patch "/unhide", to: "comments#unhide"
      patch "/admin_delete", to: "comments#admin_delete"
      collection do
        post "/moderator_create", to: "comments#moderator_create"
      end
    end
    resources :comment_mutes, only: %i[update]
    resources :users, only: %i[index], defaults: { format: :json } do # internal API
      collection do
        resources :devices, only: %i[create destroy]
      end
    end
    namespace :users do
      resource :settings, only: %i[update]
      resource :notification_settings, only: %i[update]
    end
    resources :users, only: %i[update]
    resources :reactions, only: %i[index create]
    resources :response_templates, only: %i[index create edit update destroy]
    resources :feedback_messages, only: %i[index create]
    resources :organizations, only: %i[update create destroy]
    resources :follows, only: %i[show create] do
      collection do
        get "/bulk_show", to: "follows#bulk_show"
        patch "/bulk_update", to: "follows#bulk_update"
      end
    end
    resources :image_uploads, only: [:create]
    resources :notifications, only: [:index]
    resources :tags, only: [:index] do
      collection do
        get "/onboarding", to: "tags#onboarding"
        get "/suggest", to: "tags#suggest", defaults: { format: :json }
      end
    end
    resources :stripe_active_cards, only: %i[create update destroy]
    resources :github_repos, only: %i[index] do
      collection do
        post "/update_or_create", to: "github_repos#update_or_create"
      end
    end
    resources :videos, only: %i[index create new]
    resources :video_states, only: [:create]
    resources :twilio_tokens, only: [:show]
    resources :html_variant_trials, only: [:create]
    resources :html_variant_successes, only: [:create]
    resources :tag_adjustments, only: %i[create destroy]
    resources :rating_votes, only: [:create]
    resources :page_views, only: %i[create update]
    resources :listings, only: %i[index new create edit update destroy dashboard]
    resources :credits, only: %i[index new create] do
      get "purchase", on: :collection, to: "credits#new"
    end
    resources :reading_list_items, only: [:update]
    resources :poll_votes, only: %i[show create]
    resources :poll_skips, only: [:create]
    resources :profile_pins, only: %i[create update]
    resources :display_ad_events, only: [:create]
    resources :badges, only: [:index]
    resources :user_blocks, param: :blocked_id, only: %i[show create destroy]
    resources :podcasts, only: %i[new create]
    resources :article_approvals, only: %i[create]
    resources :sidebars, only: %i[show]
    resources :profile_preview_cards, only: %i[show]
    resources :user_subscriptions, only: %i[create] do
      collection do
        get "/subscribed", action: "subscribed"
      end
    end
    namespace :followings, defaults: { format: :json } do
      get :users
      get :tags
      get :organizations
      get :podcasts
    end

    resource :onboarding, only: :show
    resources :profiles, only: %i[update]
    resources :profile_field_groups, only: %i[index], defaults: { format: :json }

    resources :liquid_tags, only: %i[index], defaults: { format: :json }

    resources :discussion_locks, only: %i[create destroy]

    get "/verify_email_ownership", to: "email_authorizations#verify", as: :verify_email_authorizations
    get "/search/tags", to: "search#tags"
    get "/search/listings", to: "search#listings"
    get "/search/usernames", to: "search#usernames"
    get "/search/feed_content", to: "search#feed_content"
    get "/search/reactions", to: "search#reactions"
    get "/listings/dashboard", to: "listings#dashboard"
    get "/listings/:category", to: "listings#index", as: :listing_category
    get "/listings/:category/:slug", to: "listings#index", as: :listing_slug
    get "/listings/:category/:slug/:view", to: "listings#index",
                                           constraints: { view: /moderate/ }
    get "/listings/:category/:slug/delete_confirm", to: "listings#delete_confirm"
    delete "/listings/:category/:slug", to: "listings#destroy"
    get "/notifications/:filter", to: "notifications#index", as: :notifications_filter
    get "/notifications/:filter/:org_id", to: "notifications#index", as: :notifications_filter_org
    get "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#show"
    post "/notification_subscriptions/:notifiable_type/:notifiable_id", to: "notification_subscriptions#upsert"
    patch "/onboarding_update", to: "users#onboarding_update"
    patch "/onboarding_checkbox_update", to: "users#onboarding_checkbox_update"
    patch "/onboarding_notifications_checkbox_update",
          to: "users/notification_settings#onboarding_notifications_checkbox_update"
    get "email_subscriptions/unsubscribe"

    get "/internal", to: redirect("/admin")
    get "/internal/:path", to: redirect("/admin/%{path}")

    get "/social_previews/article/:id", to: "social_previews#article", as: :article_social_preview
    get "/social_previews/user/:id", to: "social_previews#user", as: :user_social_preview
    get "/social_previews/organization/:id", to: "social_previews#organization", as: :organization_social_preview
    get "/social_previews/tag/:id", to: "social_previews#tag", as: :tag_social_preview
    get "/social_previews/listing/:id", to: "social_previews#listing", as: :listing_social_preview
    get "/social_previews/comment/:id", to: "social_previews#comment", as: :comment_social_preview

    get "/async_info/base_data", controller: "async_info#base_data", defaults: { format: :json }

    post "users/join_org", to: "users#join_org"
    post "users/leave_org/:organization_id", to: "users#leave_org", as: :users_leave_org
    post "users/add_org_admin", to: "users#add_org_admin"
    post "users/remove_org_admin", to: "users#remove_org_admin"
    post "users/remove_from_org", to: "users#remove_from_org"
    delete "users/remove_identity", to: "users#remove_identity"
    post "users/request_destroy", to: "users#request_destroy", as: :user_request_destroy

app/controllers/admin/tags/moderators_controller.rb
module Admin
  module Tags
    class ModeratorsController < Admin::ApplicationController
      def authorization_resource
        Tag
      end

      after_action only: %i[create destroy] do
        Audit::Logger.log(:moderator, current_user, params.dup)
      end

      def create
        user = User.find_by(id: tag_params[:user_id])
        unless user
          flash[:error] = "Error: User ID ##{tag_params[:user_id]} was not found"
          return redirect_to edit_admin_tag_path(params[:tag_id])
        end

        notification_setting = user.notification_setting
        if notification_setting.update(email_tag_mod_newsletter: true)
          TagModerators::Add.call([user.id], [params[:tag_id]])
          flash[:success] = "#{user.username} was added as a tag moderator!"
        else
          flash[:error] = "Error: User ID ##{tag_params[:user_id]} was not found,
          or their account has errors: #{notification_setting.errors_as_sentence}"
        end
        redirect_to edit_admin_tag_path(params[:tag_id])
      end

      def destroy
        user = User.find_by(id: tag_params[:user_id])
        unless user
          flash[:error] = "Error: User ID ##{tag_params[:user_id]} was not found"
          return redirect_to edit_admin_tag_path(params[:tag_id])
        end

        notification_setting = user.notification_setting
        tag = Tag.find_by(id: params[:tag_id])
        if notification_setting.update(email_tag_mod_newsletter: false)
          TagModerators::Remove.call(user, tag)
          flash[:success] = "@#{user.username} - ID ##{user.id} was removed as a tag moderator."
        else
          flash[:error] = "Error: User ID ##{tag_params[:user_id]} was not found,
          or their account has errors: #{notification_setting.errors_as_sentence}"
        end
        redirect_to edit_admin_tag_path(tag.id)
      end

      private

      def tag_params
        params.require(:tag).permit(:user_id)
      end
    end
  end
end

app/controllers/admin/tags_controller.rb
module Admin
  class TagsController < Admin::ApplicationController
    layout "admin"

    ALLOWED_PARAMS = %i[
      id supported rules_markdown short_summary pretty_name bg_color_hex
      text_color_hex user_id alias_for badge_id requires_approval
      social_preview_template wiki_body_markdown submission_template
    ].freeze

    before_action :set_default_options, only: %i[index]
    before_action :badges_for_options, only: %i[new create edit update]
    after_action only: [:update] do
      Audit::Logger.log(:moderator, current_user, params.dup)
    end

    def index
      @q = Tag.ransack(params[:q])
      @tags = @q.result.page(params[:page]).per(50)
    end

    def new
      @tag = Tag.new
    end

    def create
      @tag = Tag.new(tag_params)
      @tag.name = params[:tag][:name].downcase

      if @tag.save
        flash[:success] = "#{@tag.name} has been created!"
        redirect_to edit_admin_tag_path(@tag)
      else
        flash[:danger] = @tag.errors_as_sentence
        render :new
      end
    end

    def edit
      @tag = Tag.find(params[:id])
      @tag_moderators = User.with_role(:tag_moderator, @tag).select(:id, :username)
    end

    def update
      @tag = Tag.find(params[:id])
      if @tag.update(tag_params)
        ::Tags::AliasRetagWorker.perform_async(@tag.id) if tag_alias_updated?
        flash[:success] = "#{@tag.name} tag successfully updated!"
      else
        flash[:error] = "The tag update failed: #{@tag.errors_as_sentence}"
      end
      redirect_to edit_admin_tag_path(@tag.id)
    end

    private

    def set_default_options
      params[:q] = { supported_not_null: "true" } if params[:q].blank?
      params[:q][:s] = "taggings_count desc" if params[:q][:s].blank?
    end

    def badges_for_options
      @badges_for_options = Badge.pluck(:title, :id)
    end

    def tag_params
      params.require(:tag).permit(ALLOWED_PARAMS)
    end

    def tag_alias_updated?
      tag_params[:alias_for].present?
    end
  end
end

app/controllers/api/v0/tags_controller.rb
module Api
  module V0
    class TagsController < ApiController
      before_action :set_cache_control_headers, only: %i[index]

      ATTRIBUTES_FOR_SERIALIZATION = %i[id name bg_color_hex text_color_hex].freeze
      private_constant :ATTRIBUTES_FOR_SERIALIZATION

      def index
        page = params[:page]
        per_page = (params[:per_page] || 10).to_i
        num = [per_page, 1000].min

        @tags = Tag.select(ATTRIBUTES_FOR_SERIALIZATION)
          .order(taggings_count: :desc)
          .page(page).per(num)

        set_surrogate_key_header Tag.table_key, @tags.map(&:record_key)
      end
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_cache_control_headers, only: %i[index onboarding]
  before_action :authenticate_user!, only: %i[edit update]
  after_action :verify_authorized

  ATTRIBUTES_FOR_SERIALIZATION = %i[id name bg_color_hex text_color_hex].freeze
  INDEX_API_ATTRIBUTES = %i[name rules_html].freeze
  TAGS_ALLOWED_PARAMS = %i[
    wiki_body_markdown
    rules_markdown
    short_summary
    pretty_name
    bg_color_hex
    text_color_hex
  ].freeze

  def index
    skip_authorization
    @tags_index = true
    @tags = Tag.where(alias_for: [nil, ""]).includes(:sponsorship).order(hotness_score: :desc).limit(100)
  end

  def edit
    @tag = Tag.find_by!(name: params[:tag])
    authorize @tag
  end

  def update
    @tag = Tag.find(params[:id])
    authorize @tag
    if @tag.errors.messages.blank? && @tag.update(tag_params)
      flash[:success] = "Tag successfully updated! 👍 "
      redirect_to "#{URL.tag_path(@tag)}/edit"
    else
      flash[:error] = @tag.errors.full_messages
      render :edit
    end
  end

  def admin
    tag = Tag.find_by!(name: params[:tag])
    authorize tag
    redirect_to edit_admin_tag_path(tag.id)
  end

  def onboarding
    skip_authorization

    @tags = Tag.where(name: Settings::General.suggested_tags)
      .select(ATTRIBUTES_FOR_SERIALIZATION)

    set_surrogate_key_header Tag.table_key, @tags.map(&:record_key)
  end

  def suggest
    skip_authorization
    tags = Tag.supported.order(hotness_score: :desc).limit(100).select(INDEX_API_ATTRIBUTES)
    render json: tags.as_json(only: INDEX_API_ATTRIBUTES)
  end

  private

  def convert_empty_string_to_nil
    # nil plays nicely with our hex colors, whereas empty string doesn't
    params[:tag][:text_color_hex] = nil if params[:tag][:text_color_hex] == ""
    params[:tag][:bg_color_hex] = nil if params[:tag][:bg_color_hex] == ""
  end

  def tag_params
    convert_empty_string_to_nil
    params.require(:tag).permit(TAGS_ALLOWED_PARAMS)
  end

  private_constant :ATTRIBUTES_FOR_SERIALIZATION
end

app/views/tags/_liquid.html.erb
<div class="ltag__tag ltag__tag__id__<%= tag.id %>" style="border-color:<%= dark_color %>;box-shadow: 3px 3px 0px <%= dark_color %>;">
  <style>
    .ltag__tag__id__<%= tag.id %> .follow-action-button{
      background-color: <%= tag.bg_color_hex %> !important;
      color: <%= tag.text_color_hex %> !important;
      border-color: <%= tag.bg_color_hex.to_s.casecmp("#ffffff").zero? ? tag.text_color_hex : tag.bg_color_hex %> !important;
    }
  </style>
    <div class="ltag__tag__content">
      <h2>#<a href="<%= URL.tag tag %>" class="ltag__tag__link"><%= tag.name %></a> <%= follow_btn %></h2>
      <div class="ltag__tag__summary">
        <%= tag.short_summary %>
      </div>
    </div>
</div>

app/views/tags/edit.html.erb
<% title t("views.tags.edit.meta.title", tag: @tag.name) %>

<main id="main-content" class="crayons-layout crayons-layout--limited-m">
  <header class="crayons-card flex items-center justify-between branded-4 p-3 pr-1 m:pr-5 m:p-6 m:pt-5" style="border-top-color: <%= @tag.bg_color_hex %>">
    <h1 class="crayons-title">
      <% if @tag_model && @tag_model.pretty_name.present? %>
        <%= @tag_model.pretty_name %>
      <% else %>
        <span class="opacity-50">#</span><%= @tag %>
      <% end %>
    </h1>
    <div class="flex">
      <% if current_user.has_role?(:super_admin) || current_user.has_role?(:admin) %>
        <a href="<%= edit_admin_tag_path(@tag.id) %>" class="crayons-btn crayons-btn--ghost" data-no-instant><%= t("views.tags.edit.admin") %></a>
      <% end %>
      <a target="_blank" rel="noopener" href="https://admin.forem.com/docs/forem-basics/tags#editing-a-tag" class="crayons-btn crayons-btn--ghost"><%= t("views.tags.edit.help") %></a>
      <a href="/t/<%= @tag %>" class="crayons-btn crayons-btn--ghost"><%= t("views.tags.edit.view") %></a>
    </div>
  </header>

  <%= form_tag("/tag/#{@tag.id}", method: :patch, class: "crayons-card p-4 m:p-6 grid gap-4") do %>
    <% if flash[:success] %>
      <div class="crayons-notice crayons-notice--success">
        <%= flash[:success] %>
      </div>
    <% elsif flash[:error] %>
      <div class="crayons-notice crayons-notice--danger">
        <ul>
          <% flash[:error].each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% label_i18n = ->(param) { label_tag param, t("views.tags.edit.form.#{param}.label") } %>
    <div class="crayons-field">
      <%= label_tag :pretty_name, nil, class: "crayons-field__label" %>
      <%= text_field_tag "tag[pretty_name]", @tag.pretty_name, placeholder: t("views.tags.edit.form.pretty_name.placeholder"), class: "crayons-textfield" %>
    </div>
    <div class="flex gap-4">
      <div class="crayons-field flex-1">
        <%= label_tag :bg_color_hex, nil, class: "crayons-field__label" %>
        <%= color_field_tag "tag[bg_color_hex]", @tag.bg_color_hex.presence || "#000000", placeholder: "#000000", class: "crayons-color-selector crayons-color-selector--full" %>
      </div>
      <div class="crayons-field flex-1">
        <%= label_tag :text_color_hex, nil, class: "crayons-field__label" %>
        <%= color_field_tag "tag[text_color_hex]", @tag.text_color_hex.presence || "#ffffff", placeholder: "#ffffff", class: "crayons-color-selector crayons-color-selector--full" %>
      </div>
    </div>
    <div class="crayons-notice crayons-notice--warning">We will soon update how tags are being displayed. Please define tag's primary color in "Bg color hex" field - the other one ("Text color hex") will be deprecated.</div>
    <div class="crayons-field">
      <%= label_tag :short_summary, nil, class: "crayons-field__label" %>
      <%= text_area_tag "tag[short_summary]", @tag.short_summary, placeholder: t("views.tags.edit.form.short_summary.placeholder"), class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= label_tag :wiki_body_markdown, nil, class: "crayons-field__label" %>
      <%= text_area_tag "tag[wiki_body_markdown]", @tag.wiki_body_markdown, placeholder: t("views.tags.edit.form.wiki_body_markdown.placeholder"), class: "crayons-textfield" %>
    </div>
    <div class="crayons-field">
      <%= label_tag :rules_markdown, nil, class: "crayons-field__label" %>
      <%= text_area_tag "tag[rules_markdown]", @tag.rules_markdown, placeholder: t("views.tags.edit.form.rules_markdown.placeholder"), class: "crayons-textfield" %>
    </div>
    <div>
      <%= submit_tag t("views.tags.edit.form.submit"), class: "crayons-btn" %>
    </div>
  <% end %>
</main>

app/views/tags/index.html.erb
<% title t("views.tags.meta.title") %>

<%= content_for :page_meta do %>
  <link rel="canonical" href="<%= app_url("/tags") %>" />
  <meta name="description" content="<%= t("views.tags.meta.description", community: community_name) %>">
  <%= meta_keywords_default %>

  <meta property="og:type" content="article" />
  <meta property="og:url" content="<%= app_url("/tags") %>" />
  <meta property="og:title" content="<%= t("views.tags.meta.description", community: community_name) %>" />
  <meta property="og:image" content="<%= Settings::General.main_social_image %>" />
  <meta property="og:description" content="<%= t("views.tags.meta.og.description", community: community_name) %>" />
  <meta property="og:site_name" content="<%= community_name %>" />

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@<%= Settings::General.social_media_handles["twitter"] %>">
  <meta name="twitter:title" content="<%= t("views.tags.meta.description", community: community_name) %>">
  <meta name="twitter:description" content="<%= t("views.tags.meta.og.description", community: community_name) %>">
  <meta name="twitter:image:src" content="<%= Settings::General.main_social_image %>">
<% end %>

<main id="main-content" class="crayons-layout crayons-layout--header-inside">
  <header class="crayons-page-header">
    <h1 class="crayons-title"><%= t("views.tags.heading") %></h1>
    <%= link_to t("views.tags.following_tags"), dashboard_following_tags_path, class: "crayons-btn crayons-btn--ghost" %>
  </header>

  <div class="grid gap-3 m:gap-4 l:gap-6 m:grid-cols-2 l:grid-cols-3 px-3 m:px-0 pb-3" data-follow-button-container="true">
    <% @tags.each do |tag| %>
      <div class="tag-card crayons-card branded-4 p-3 pt-2 m:p-6 m:pt-4 relative" style="border-top-color: <%= tag.bg_color_hex %>; ">
        <h3 class="mb-1 -ml-2">
          <%= render_tag_link(tag.name) %>
        </h3>
        <% if tag.short_summary.present? %>
          <p class="mb-2 color-base-70 truncate-at-3"><%= sanitize tag.short_summary %></p>
        <% end %>
        <p class="mb-3 fs-s color-base-60">
          <%= t("views.tags.published", count: tag.taggings_count) %>
          <% if tag.sponsorship && tag.sponsorship.status == "live" && tag.sponsorship.expires_at > Time.current %>
          <%= t("views.tags.sponsor", org: tag.sponsorship.organization.name) %>
          <% end %>
        </p>

        <% if tag %>
          <div class="mt-auto">
            <button
              class="crayons-btn crayons-btn--secondary follow-action-button"
              data-info='{"id":<%= tag.id %>,"className":"Tag", "followStyle":"secondary", "name": "<%= tag.name %>"}'>
              <%= t("views.tags.follow") %>
            </button>
          </div>
        <% end %>

        <% if tag.badge_id && tag.badge %>
          <img src="<%= optimized_image_url(tag.badge.badge_image_url, width: 180) %>" style="width: 64px; height: 64px; transform: rotate(<%= -25 + (tag.id.digits.first * 5) %>deg);" class="right-1 bottom-1 absolute" alt="" loading="lazy" />
        <% end %>
      </div>
    <% end %>
  </div>
</main>
<%= javascript_packs_with_chunks_tag "followButtons", defer: true %>